# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 - 2025 Slavi Pantaleev
# SPDX-FileCopyrightText: 2025 Suguru Hirahara
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---

- name: Ensure InfluxDB path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0700
    owner: "{{ influxdb_uid }}"
    group: "{{ influxdb_gid }}"
  with_items:
    - {path: "{{ influxdb_base_path }}", when: true}

- name: Ensure InfluxDB data path exists
  ansible.builtin.file:
    path: "{{ item.path }}"
    state: directory
    mode: 0755
    owner: "{{ influxdb_uid }}"
    group: "{{ influxdb_gid }}"
  with_items:
    - {path: "{{ influxdb_data_path }}", when: true}

- name: Ensure InfluxDB support files installed
  ansible.builtin.template:
    src: "{{ role_path }}/templates/{{ item }}.j2"
    dest: "{{ influxdb_base_path }}/{{ item }}"
    mode: "0640"
    owner: "{{ influxdb_uid }}"
    group: "{{ influxdb_gid }}"
  with_items:
    - env
    - labels

- name: Ensure InfluxDB container image is pulled
  community.docker.docker_image:
    name: "{{ influxdb_container_image }}"
    source: "{{ 'pull' if ansible_version.major > 2 or ansible_version.minor > 7 else omit }}"
    force_source: "{{ influxdb_container_image_force_pull if ansible_version.major > 2 or ansible_version.minor >= 8 else omit }}"
    force: "{{ omit if ansible_version.major > 2 or ansible_version.minor >= 8 else influxdb_container_image_force_pull }}"

- name: Ensure InfluxDB container network is created
  community.docker.docker_network:
    enable_ipv6: "{{ devture_systemd_docker_base_ipv6_enabled }}"
    name: "{{ influxdb_container_network }}"
    driver: bridge
    driver_options: "{{ devture_systemd_docker_base_container_networks_driver_options }}"

- name: Ensure InfluxDB systemd service is present
  ansible.builtin.template:
    src: "{{ role_path }}/templates/systemd/influxdb.service.j2"
    dest: "{{ devture_systemd_docker_base_systemd_path }}/{{ influxdb_identifier }}.service"
    mode: 0644
