# SPDX-FileCopyrightText: 2023 Julian-Samuel Gebühr
# SPDX-FileCopyrightText: 2023 Slavi Pantaleev
#
# SPDX-License-Identifier: AGPL-3.0-or-later

---
- name: (Deprecation) Catch and report renamed settings
  ansible.builtin.fail:
    msg: >-
      Your configuration contains a variable, which now has a different name.
      Please change your configuration to rename the variable (`{{ item.old }}` -> `{{ item.new }}`).
  when: "item.old in vars"
  with_items:
    - { "old": "influxdb_environment_variables_extension", "new": "influxdb_environment_variables_additional_variables" }

- name: Fail if required InfluxDB settings not defined
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`).
  when: "vars[item] == ''"
  with_items:
    - influxdb_hostname

- name: Fail when not all initial settings are missing
  ansible.builtin.fail:
    msg: >-
      You need to define a required configuration setting (`{{ item }}`) to correctly set up a initial user, organization and bucket.
  when: "influxdb_init and vars[item] == ''"
  with_items:
    - influxdb_init_username
    - influxdb_init_password
    - influxdb_init_org
    - influxdb_init_bucket
